from information_extraction import answer_question, process_data_from_input_file

process_data_from_input_file()
answer_question('What\'s the name of Mary\'s dog?')
answer_question('Who does Chris like?')
answer_question('Who does Mary like?')
answer_question('who has a cat?')
answer_question('Who is flying to Japan?')
answer_question('Does Chris like Mary?')
answer_question('who likes Mary?')
answer_question('when is Mary flying to France?')
answer_question('Who is going to Mexico?')
answer_question('What\'s the name of Chris\'s cat?')
answer_question('When is Sally going to Japan?')
answer_question('Does Mary like Sally?')
answer_question('when is Mary traveling to france?')